# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class IsccIndex(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str,
        Field(
            description="Short unique name of the index (valid code identifier)",
            examples=["default"],
            max_length=32,
            min_length=1,
            pattern="^[a-z][a-z0-9]*$",
        ),
    ]
    items: Annotated[
        int | None,
        Field(description="Number of ISCCs in the index (server-generated, read-only)", examples=[150000], ge=0),
    ] = None
    size: Annotated[
        int | None, Field(description="Size of index in megabytes (server-generated, read-only)", examples=[42], ge=0)
    ] = None
