# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class IsccIndex(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str | None,
        Field(
            description="Short unique name of the index",
            examples=["default"],
            max_length=32,
            min_length=1,
            pattern="^[a-z]([a-z0-9-]*[a-z0-9])?$",
        ),
    ] = None
    items: Annotated[int | None, Field(description="Number of ISCCs in the index", examples=[150000], ge=0)] = None
    size: Annotated[int | None, Field(description="Size of index in megabytes", examples=[42], ge=0)] = None
