openapi: 3.1.0
info:
  title: ISCC-VDB API
  description: A Scalable Nearest Neighbor Search Multi-Index for the International Standard Content Code (ISCC)
  version: 0.1.0
servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /indexes:
    get:
      summary: List all indexes
      description: Returns a list of all available ISCC indexes with their metadata
      operationId: listIndexes
      tags:
        - indexes
      responses:
        '200':
          description: Successful response with list of indexes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IsccIndex'
              example:
                - name: "default"
                  items: 150000
                  size: 42
    post:
      summary: Create a new index
      description: Creates a new ISCC index with the specified name. The index is initialized empty with 0 items.
      operationId: createIndex
      tags:
        - indexes
      requestBody:
        required: true
        description: Index configuration with unique name
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IsccIndex'
            example:
              name: "myindex"
      responses:
        '201':
          description: Index successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IsccIndex'
              example:
                name: "myindex"
                items: 0
                size: 0
        '400':
          description: Invalid request (e.g., invalid name format)
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
              example:
                detail: "Invalid index name format"
        '409':
          description: Index with this name already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
              example:
                detail: "Index 'myindex' already exists"
  /indexes/{name}:
    delete:
      summary: Delete an index
      description: Permanently deletes an ISCC index and all its data
      operationId: deleteIndex
      tags:
        - indexes
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the index to delete
          schema:
            type: string
            pattern: "^[a-z][a-z0-9]*$"
            minLength: 1
            maxLength: 32
            example: "myindex"
      responses:
        '204':
          description: Index successfully deleted (no content returned)
        '400':
          description: Invalid index name format
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
              example:
                detail: "Invalid index name format"
        '404':
          description: Index not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
              example:
                detail: "Index 'myindex' not found"

components:
  schemas:
    IsccIndex:
      $ref: './IsccIndex.yaml'
